[2023-07-19T14:59:41.080+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.extract_api_data manual__2023-07-19T14:59:38.623731+00:00 [queued]>
[2023-07-19T14:59:41.108+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.extract_api_data manual__2023-07-19T14:59:38.623731+00:00 [queued]>
[2023-07-19T14:59:41.108+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-19T14:59:41.123+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_api_data> on 2023-07-19 14:59:38.623731+00:00
[2023-07-19T14:59:41.133+0000] {standard_task_runner.py:57} INFO - Started process 133 to run task
[2023-07-19T14:59:41.151+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl', 'extract_api_data', 'manual__2023-07-19T14:59:38.623731+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpcmy54bhz']
[2023-07-19T14:59:41.176+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask extract_api_data
[2023-07-19T14:59:41.320+0000] {task_command.py:410} INFO - Running <TaskInstance: etl.extract_api_data manual__2023-07-19T14:59:38.623731+00:00 [running]> on host 6f676df8422e
[2023-07-19T14:59:41.446+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Carvalho' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='extract_api_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-19T14:59:38.623731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-19T14:59:38.623731+00:00'
[2023-07-19T14:59:41.455+0000] {logging_mixin.py:150} INFO - An error occurred while making the request: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2023-07-19T14:59:41.455+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 99, in extract_api_data
    response = requests.get(base_url, params={'id': employee_id})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 498, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2023-07-19T14:59:41.470+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=etl, task_id=extract_api_data, execution_date=20230719T145938, start_date=20230719T145941, end_date=20230719T145941
[2023-07-19T14:59:41.483+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task extract_api_data (Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?; 133)
[2023-07-19T14:59:41.514+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-19T14:59:41.555+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
