[2023-07-19T15:04:45.042+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.extract_parquet_data manual__2023-07-19T15:03:40.086172+00:00 [queued]>
[2023-07-19T15:04:45.068+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.extract_parquet_data manual__2023-07-19T15:03:40.086172+00:00 [queued]>
[2023-07-19T15:04:45.068+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-19T15:04:45.109+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_parquet_data> on 2023-07-19 15:03:40.086172+00:00
[2023-07-19T15:04:45.118+0000] {standard_task_runner.py:57} INFO - Started process 396 to run task
[2023-07-19T15:04:45.126+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl', 'extract_parquet_data', 'manual__2023-07-19T15:03:40.086172+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpwsvk5ps2']
[2023-07-19T15:04:45.129+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask extract_parquet_data
[2023-07-19T15:04:45.188+0000] {task_command.py:410} INFO - Running <TaskInstance: etl.extract_parquet_data manual__2023-07-19T15:03:40.086172+00:00 [running]> on host 6f676df8422e
[2023-07-19T15:04:45.339+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Carvalho' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='extract_parquet_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-19T15:03:40.086172+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-19T15:03:40.086172+00:00'
[2023-07-19T15:04:45.411+0000] {logging_mixin.py:150} INFO - An unexpected error has occured: Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType
[2023-07-19T15:04:45.412+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 133, in extract_parquet_data
    df = pd.read_parquet(base_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 240, in read
    path_or_handle, columns=columns, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 2939, in read_table
    thrift_container_size_limit=thrift_container_size_limit,
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 2480, in __init__
    ignore_prefixes=ignore_prefixes)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 784, in dataset
    'instead of the given type: {}'.format(type(source).__name__)
TypeError: Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType
[2023-07-19T15:04:45.426+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=etl, task_id=extract_parquet_data, execution_date=20230719T150340, start_date=20230719T150445, end_date=20230719T150445
[2023-07-19T15:04:45.452+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 18 for task extract_parquet_data (Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType; 396)
[2023-07-19T15:04:45.497+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-19T15:04:45.535+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
